
import torch
from torch import nn

# generated by GPT
class LinearWithDropIn(nn.Module):

    def __init__(self, in_features, out_features, bias=True,
                 rate=0.1, mean=1.1, std=0.05):
        
        super().__init__()

        self.linear = nn.Linear(in_features, out_features, bias=bias)

        self.rate = rate
        self.mean = mean
        self.std = std

        self._drop_in_active = True


    def forward(self, x):

        if not self._drop_in_active:
            return self.linear(x)

        else:

            # Randomly select weights
            mask = torch.rand_like(self.linear.weight) < self.rate

            # Generate multiplicative factors
            multipliers = torch.abs(torch.randn_like(self.linear.weight)) * self.std + self.mean

            # Save original weights
            original_weight = self.linear.weight.data.clone()

            try:

                # Temporarily modify selected weights
                self.linear.weight.data[mask] *= multipliers[mask]

                # Normal Linear forward
                return self.linear(x)

            finally:

                # Always restore original weights
                self.linear.weight.data.copy_(original_weight)

    def turn_off_drop_in(self) -> None:
        self._drop_in_active = False
