
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import numpy as np

# chart code generated by ChatGPT
def plot_loss(train_loss, val_loss):
    """
    Plots training and optionally validation loss over epochs.

    Parameters
    ----------
    train_loss : list or array-like
        Training loss values per epoch.
    val_loss : list or array-like, optional
        Validation loss values per epoch.
    """
    epochs = range(1, len(train_loss) + 1)

    plt.figure()
    plt.plot(epochs, train_loss, label="Training Loss")
    if len(val_loss) != len(train_loss):
       raise ValueError("train_loss and val_loss must have the same length")
    plt.plot(epochs, val_loss, label="Validation Loss")

    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training vs Validation Loss")
    plt.legend()
    plt.grid(True)

    plt.show()

# chart code generated by ChatGPT
def plot_confusion_matrix_labeled(y_true, y_pred, class_names=None, normalize=None):
    """
    Confusion matrix with explicit TN, FP, FN, TP labels (binary only).
    """

    y_true = y_true.detach().numpy()
    y_pred = y_pred.detach().numpy()

    labels = np.unique(np.concatenate([y_true, y_pred]))
    if len(labels) != 2:
        raise ValueError("TP/FP/TN/FN labeling only works for binary classification")

    cm = confusion_matrix(y_true, y_pred, labels=labels, normalize=normalize)

    disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                  display_labels=class_names if class_names else labels)
    disp.plot()

    ax = disp.ax_
    ax.set_title("Confusion Matrix")

    # Clear default text
    for text in ax.texts:
        text.set_text("")

    # Add custom labels
    names = [["TN", "FP"],
             ["FN", "TP"]]

    for i in range(2):
        for j in range(2):
            value = cm[i, j]
            if normalize:
                text = f"{names[i][j]}\n{value:.2f}"
            else:
                text = f"{names[i][j]}\n{int(value)}"

            ax.text(j, i, text,
                    ha="center", va="center",
                    color="white" if value > cm.max()/2 else "black")

    plt.show()
